condor_submit jobs/005um/xray_copper.job -name ettore
condor_submit jobs/010um/xray_copper.job -name ettore
condor_submit jobs/015um/xray_copper.job -name ettore
condor_submit jobs/020um/xray_copper.job -name ettore
condor_submit jobs/025um/xray_copper.job -name ettore
condor_submit jobs/030um/xray_copper.job -name ettore
condor_submit jobs/035um/xray_copper.job -name ettore
condor_submit jobs/040um/xray_copper.job -name ettore
condor_submit jobs/045um/xray_copper.job -name ettore
condor_submit jobs/050um/xray_copper.job -name ettore
condor_submit jobs/055um/xray_copper.job -name ettore
condor_submit jobs/060um/xray_copper.job -name ettore
condor_submit jobs/065um/xray_copper.job -name ettore
condor_submit jobs/070um/xray_copper.job -name ettore
condor_submit jobs/075um/xray_copper.job -name ettore
condor_submit jobs/080um/xray_copper.job -name ettore
condor_submit jobs/085um/xray_copper.job -name ettore
condor_submit jobs/090um/xray_copper.job -name ettore
condor_submit jobs/095um/xray_copper.job -name ettore
condor_submit jobs/100um/xray_copper.job -name ettore
